from src.api.entities_api.orchestration.mixins import (
    AssistantCacheMixin,
    ClientFactoryMixin,
    CodeInterpreterMixin,
    ConsumerToolHandlersMixin,
    ContextMixin,
    DelegationMixin,
    FileSearchMixin,
    JsonUtilsMixin,
    NativeExecMixin,
    NetworkInventoryMixin,
    PlatformToolHandlersMixin,
    ScratchpadMixin,
    ServiceRegistryMixin,
    ShellExecutionMixin,
    StreamingMixin,
    ToolRoutingMixin,
    WebSearchMixin,
)


class _ProviderMixins(
    ServiceRegistryMixin,
    ClientFactoryMixin,
    AssistantCacheMixin,
    JsonUtilsMixin,
    NativeExecMixin,
    ContextMixin,
    DelegationMixin,
    ToolRoutingMixin,
    PlatformToolHandlersMixin,
    ConsumerToolHandlersMixin,
    CodeInterpreterMixin,
    ShellExecutionMixin,
    FileSearchMixin,
    WebSearchMixin,
    ScratchpadMixin,
    NetworkInventoryMixin,
):
    """Flat bundle for Provider Mixins."""
