[supervisord]
nodaemon=true

[program:entities_api]
command=uvicorn --app-dir /app src.api.entities_api.app:app --host 0.0.0.0 --port 9000 --no-access-log
directory=/app
autostart=true
autorestart=true
startretries=10
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0

[program:file_purge_daemon]
command=python /app/src/api/entities_api/daemons/purge_expired_files.py
directory=/app
autostart=true
autorestart=true
startretries=5
startsecs=10
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
environment=PYTHONPATH="/app/src/api",SHARED_PATH="/app/shared_data"

[program:purge_soft_deleted_files]
command=python /app/src/api/entities_api/cli/purge_soft_deleted_files.py
directory=/app
autostart=true
autorestart=true
startretries=5
startsecs=10
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
environment=PYTHONPATH="/app/src/api",SHARED_PATH="/app/shared_data"

[program:purge_soft_deleted_vector_stores]
command=python /app/src/api/entities_api/cli/purge_soft_deleted_vector_stores.py
directory=/app
autostart=true
autorestart=true
startretries=5
startsecs=10
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
environment=PYTHONPATH="/app/src/api",QDRANT_HOST="qdrant",QDRANT_PORT="6333"

[program:purge_orphaned_threads]
command=python /app/src/api/entities_api/daemons/purge_orphaned_threads.py
directory=/app
autostart=true
autorestart=true
startretries=5
startsecs=10
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
environment=PYTHONPATH="/app/src/api"

[program:purge_expired_runs]
command=python /app/src/api/entities_api/daemons/purge_expired_runs.py
directory=/app
autostart=true
autorestart=true
startretries=5
startsecs=10
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
environment=PYTHONPATH="/app/src/api"