version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: my_mysql_cosmic_catalyst
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: v5C9UurE3wmqix2C
      MYSQL_DATABASE: cosmic_catalyst
      MYSQL_USER: ollama
      MYSQL_PASSWORD: 3e4Qv5uo2Cg31zC1
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - custom_network

  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    container_name: fastapi_cosmic_catalyst
    restart: always
    environment:
      - DATABASE_URL=mysql+pymysql://ollama:3e4Qv5uo2Cg31zC1@db:3306/cosmic_catalyst
    ports:
      - "9000:9000"
    depends_on:
      - db
    networks:
      - custom_network

networks:
  custom_network:
    driver: bridge

volumes:
  mysql_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${HOME}/.ollama/mysql_data
