services:
  db:
    image: mysql:8.0
    container_name: my_mysql_cosmic_catalyst
    restart: always
    env_file:
      - .env
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - custom_network

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fastapi_cosmic_catalyst
    restart: always
    environment:
      - DATABASE_URL=mysql+pymysql://${MYSQL_USER}:${MYSQL_PASSWORD}@db:3306/${MYSQL_DATABASE}
    ports:
      - "9090:9090"
    depends_on:
      - db
    networks:
      - custom_network

networks:
  custom_network:
    driver: bridge

volumes:
  mysql_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${HOME}/.ollama/mysql_data