version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: my_mysql_cosmic_catalyst
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: v5C9UurE3wmqix2C
      MYSQL_DATABASE: cosmic_catalyst
      MYSQL_USER: ollama
      MYSQL_PASSWORD: 3e4Qv5uo2Cg31zC1
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3307:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - cosmic_network

  qdrant:
    image: qdrant/qdrant:latest
    container_name: qdrant_server
    restart: always
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - qdrant_storage:/qdrant/storage
    networks:
      - cosmic_network

  sandbox:
    build:
      context: .
      dockerfile: Dockerfile.sandbox
    container_name: sandbox_server
    restart: always
    cap_add:
      - SYS_ADMIN
    security_opt:
      - seccomp:unconfined
    devices:
      - /dev/fuse
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - cosmic_network

  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    container_name: fastapi_cosmic_catalyst
    restart: always
    environment:
      - DATABASE_URL=mysql+pymysql://ollama:3e4Qv5uo2Cg31zC1@db:3306/cosmic_catalyst
      - SANDBOX_SERVER_URL=http://sandbox:8000
      - QDRANT_URL=http://qdrant:6333
    ports:
      - "9000:9000"
    depends_on:
      db:
        condition: service_healthy
      qdrant:
        condition: service_started
      sandbox:
        condition: service_started
    networks:
      - cosmic_network

  initializer:
    build:
      context: .
      dockerfile: Dockerfile.initializer
    container_name: assistant_initializer
    restart: "no"  # Runs once and exits
    depends_on:
      api:
        condition: service_started
    environment:
      - API_URL=http://api:9000
    networks:
      - cosmic_network

volumes:
  mysql_data:
  qdrant_storage:

networks:
  cosmic_network:
    driver: bridge
