version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: my_mysql_cosmic_catalyst
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: v5C9UurE3wmqix2C
      MYSQL_DATABASE: cosmic_catalyst
      MYSQL_USER: ollama
      MYSQL_PASSWORD: 3e4Qv5uo2Cg31zC1
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3307:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    container_name: fastapi_cosmic_catalyst
    restart: always
    environment:
      - DATABASE_URL=mysql+pymysql://ollama:3e4Qv5uo2Cg31zC1@db:3306/cosmic_catalyst
      - SANDBOX_SERVER_URL=http://sandbox:8000
      - QDRANT_URL=http://qdrant:6333  # Added Qdrant URL
    ports:
      - "9000:9000"
    depends_on:
      db:
        condition: service_healthy
      sandbox:
        condition: service_started
      qdrant:
        condition: service_healthy  # Ensure Qdrant is healthy before starting the API
    command: ["./wait-for-it.sh", "db:3306", "--", "uvicorn", "entities_api.main:app", "--host", "0.0.0.0", "--port", "9000"]
    volumes:
      - C:/Users/franc/Models/HuggingFace:/app/models

  sandbox:
    build:
      context: .
      dockerfile: Dockerfile.sandbox
    container_name: sandbox_server
    restart: always
    cap_add:
      - SYS_ADMIN  # Required for Firejail
    security_opt:
      - seccomp:unconfined  # Required for Firejail
    devices:
      - /dev/fuse  # Required for Firejail
    ports:
      - "8000:8000"  # Expose the port for the sandbox server
    depends_on:
      db:
        condition: service_healthy  # If sandbox depends on db
    volumes:
      - /tmp/sandbox_logs:/app/logs  # Optional: persist logs

  qdrant:
    image: qdrant/qdrant:v1.7.4
    container_name: qdrant_cosmic_catalyst
    restart: always
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - qdrant_data:/qdrant/storage
    environment:
      - QDRANT__SERVICE__GRPC_PORT=6334
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:6333"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  mysql_data:
    driver: local
  qdrant_data:
    driver: local