services:
  api:
    build: .
    container_name: fastapi_cosmic_catalyst
    restart: always
    ports:
      - "9090:9090"
    environment:
      - DATABASE_URL=mysql+pymysql://root:rootpassword@db:3307/cosmic_catalyst
    depends_on:
      - db
    networks:
      - api_network

  db:
    image: mysql:8.0
    container_name: mysql_cosmic_catalyst
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: cosmic_catalyst
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3307:3306"
    networks:
      - api_network
    command: --port=3307

networks:
  api_network:
    name: api_network

volumes:
  mysql_data: