"""
Level 4 Deep Research & Hybrid Supervisor Test
---------------------------------------------------
1. Tests the "Internal Loop" (Supervisor -> Worker -> Scratchpad).
2. Verifies that 'StatusEvents' are streamed while the Supervisor thinks.
3. Verifies that 'ToolCallRequestEvents' still fire for external tools (Hybrid Mode).
"""

import json
import os
import time

# Import the project classes
from config_orc_fc_deep_research import config
from dotenv import load_dotenv
from projectdavid import (
    ContentEvent,
    DecisionEvent,
    Entity,
    ReasoningEvent,
    StatusEvent,
    ToolCallRequestEvent,
)

# ------------------------------------------------------------------
# 0. CONFIGURATION
# ------------------------------------------------------------------
load_dotenv()

# ANSI Colors for Visual Debugging
CYAN = "\033[96m"  # Reasoning / Thinking
GREEN = "\033[92m"  # Content (Final Answer)
YELLOW = "\033[93m"  # External Tool Call
RED = "\033[91m"  # Errors
GREY = "\033[90m"  # Timing/Meta
MAGENTA = "\033[95m"  # Decisions
BLUE = "\033[94m"  # [NEW] Deep Research Status Updates
RESET = "\033[0m"

# CONFIG
BASE_URL = os.getenv("BASE_URL", "http://localhost:9000")
ENTITIES_API_KEY = os.getenv("ENTITIES_API_KEY")


# Choose a prompt that triggers Deep Research
# VS a prompt that triggers an External Tool
TEST_SCENARIO = "RESEARCH"  # Options: "RESEARCH", "EXTERNAL"


CURRENT_PROMPT = config.get("test_prompt")


print(f"{GREY}[CONFIG] Base URL: {BASE_URL}{RESET}")
print(f"{GREY}[CONFIG] Scenario: {TEST_SCENARIO}{RESET}")

client = Entity(base_url=BASE_URL, api_key=ENTITIES_API_KEY)
ASSISTANT_ID = config.get("assistant_id")


# ------------------------------------------------------------------
# 1. External Tool Logic (Hybrid Fallback)
# ------------------------------------------------------------------
def get_flight_times(tool_name: str, arguments: dict) -> str:
    """
    This represents an EXTERNAL tool (one the Supervisor cannot run inline).
    """
    print(f"{YELLOW}   -> [CLIENT SIDE] Executing External Tool: {tool_name}{RESET}")
    return json.dumps(
        {
            "status": "success",
            "route": "LAX-JFK",
            "flights": ["DL404 (08:00)", "AA101 (09:30)"],
        }
    )


# Registry for External Tools Only
# Note: 'delegate_research_task' is NOT here because it runs on the Server.
EXTERNAL_TOOL_REGISTRY = {
    "get_flight_times": get_flight_times,
}

# ------------------------------------------------------------------
# 2. Setup & Execution
# ------------------------------------------------------------------
print(f"\n{YELLOW}[INIT] Creating Run...{RESET}")
global_start = time.perf_counter()

thread = client.threads.create_thread()
message = client.messages.create_message(
    thread_id=thread.id,
    role="user",
    content=CURRENT_PROMPT,
    assistant_id=ASSISTANT_ID,
)
run = client.runs.create_run(assistant_id=ASSISTANT_ID, thread_id=thread.id)

# ------------------------------------------------------------------
# 3. The Stream Loop
# ------------------------------------------------------------------
stream = client.synchronous_inference_stream
stream.setup(
    thread_id=thread.id,
    assistant_id=ASSISTANT_ID,
    message_id=message.id,
    run_id=run.id,
    api_key=os.getenv("TOGETHER_API_KEY"),
)

print(f"\n{CYAN}[▶] STREAM STARTED{RESET}")
print(f"{'LATENCY':<12} | {'EVENT TYPE':<25} | {'CONTENT / PAYLOAD'}")
print("-" * 120)

last_tick = time.perf_counter()

try:
    # Use your preferred provider/model kw args here if needed by the backend
    for event in stream.stream_events(
        provider=config.get("provider"), model=config.get("model")
    ):

        # Timing
        current_tick = time.perf_counter()
        delta = current_tick - last_tick
        last_tick = current_tick
        time_str = f"[{delta:+.4f}s]"

        # --- EVENT HANDLING ---

        # A. [NEW] Status Event -> The Heartbeat of Deep Research
        if isinstance(event, StatusEvent):
            # These are generated by the Worker Loop inline
            # e.g., "Worker is researching...", "Supervisor: update_scratchpad..."

            # FIX: Access .status safely instead of .state
            content = event.message or getattr(event, "status", "processing")

            print(
                f"{GREY}{time_str:<12}{RESET} | {BLUE}{'STATUS (Worker)':<25}{RESET} | {content}"
            )

        # B. Content Event -> The tokens appearing on screen
        elif isinstance(event, ContentEvent):
            # We usually get partial tokens, let's print them cleanly or summarize
            # For this test script, we print valid text chunks
            if event.content:
                # Replace newlines for cleaner table output
                clean_content = event.content.replace("\n", "\\n")
                print(
                    f"{GREY}{time_str:<12}{RESET} | {GREEN}{'CONTENT':<25}{RESET} | {clean_content[:80]}..."
                )

        # C. Reasoning Event -> "Thinking" blocks (if using reasoning models)
        elif isinstance(event, ReasoningEvent):
            print(
                f"{GREY}{time_str:<12}{RESET} | {CYAN}{'THOUGHT':<25}{RESET} | {event.content[:50]}..."
            )

        # D. ToolCallRequestEvent -> EXTERNAL Tools Only
        elif isinstance(event, ToolCallRequestEvent):
            print(
                f"\n{YELLOW}[⚠️ EXTERNAL INTERRUPT] AI requested external tool: {event.tool_name}{RESET}"
            )

            handler = EXTERNAL_TOOL_REGISTRY.get(event.tool_name)

            if handler:
                event.execute(handler)
                print(f"{GREEN}[✓] Result Submitted. Resuming stream...{RESET}\n")
            else:
                # If we see 'delegate_research_task' here, IT MEANS THE SERVER SIDE LOOP FAILED
                # and fell back to standard dispatch.
                if event.tool_name == "delegate_research_task":
                    print(
                        f"{RED}[CRITICAL FAIL] 'delegate_research_task' leaked to client! Server loop not active.{RESET}"
                    )
                else:
                    print(f"{RED}[!] No local handler for: {event.tool_name}{RESET}")

        # E. Decision Event (Telemetry)
        elif isinstance(event, DecisionEvent):
            print(
                f"{GREY}{time_str:<12}{RESET} | {MAGENTA}{'DECISION':<25}{RESET} | {event.decision}"
            )

except Exception as e:
    print(f"{RED}[!] Error in loop: {e}{RESET}")

# ==================================================================
# SUMMARY
# ==================================================================
global_end = time.perf_counter()
total_time = global_end - global_start

print(f"\n{YELLOW}" + "=" * 60)
print(f" TOTAL TIME: {total_time:.4f}s")
print("=" * 60 + f"{RESET}\n")
