"""add agentic state columns to Assistant Run Message and Action

Revision ID: 9314d4058f78
Revises: c34a9a215b5d
Create Date: 2026-01-17 22:22:21.796231

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy import inspect
from sqlalchemy.dialects import mysql

# Import the safe DDL helpers
from migrations.utils.safe_ddl import (
    add_column_if_missing,
    drop_column_if_exists,
    safe_alter_column,
)

# revision identifiers, used by Alembic.
revision: str = "9314d4058f78"
down_revision: Union[str, None] = "c34a9a215b5d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema safely."""

    # --- Table: actions ---
    add_column_if_missing(
        "actions",
        sa.Column(
            "tool_call_id",
            sa.String(length=64),
            nullable=True,
            comment="The unique ID linking this action to a specific LLM tool request (native or generated).",
        ),
    )
    add_column_if_missing(
        "actions",
        sa.Column(
            "turn_index",
            sa.Integer(),
            nullable=True,
            comment="The iteration of the autonomous loop in which this action was triggered.",
        ),
    )

    # Safe index creation: only if missing
    bind = op.get_bind()
    insp = inspect(bind)
    indexes = [idx["name"] for idx in insp.get_indexes("actions")]
    if "ix_actions_tool_call_id" not in indexes:
        op.create_index(
            op.f("ix_actions_tool_call_id"), "actions", ["tool_call_id"], unique=False
        )

    # --- Table: assistants ---
    add_column_if_missing(
        "assistants",
        sa.Column(
            "max_turns",
            sa.Integer(),
            server_default="1",
            nullable=True,
            comment="Max number of iterative loops for Level 3 agency. 1 = Standard Level 2 (ReAct).",
        ),
    )
    add_column_if_missing(
        "assistants",
        sa.Column(
            "agent_mode",
            sa.String(length=32),
            server_default="standard",
            nullable=True,
            comment="Determines execution logic: 'standard' (Level 2) or 'autonomous' (Level 3).",
        ),
    )

    # --- Table: messages ---
    add_column_if_missing(
        "messages",
        sa.Column(
            "reasoning",
            sa.Text(length=4294967295),
            nullable=True,
            comment="Stores the internal 'thinking' or reasoning tokens from the model.",
        ),
    )
    add_column_if_missing(
        "messages",
        sa.Column(
            "tool_calls",
            sa.JSON(),
            nullable=True,
            comment="Stores the native JSON array of tool calls generated by the assistant.",
        ),
    )
    add_column_if_missing(
        "messages",
        sa.Column(
            "tool_call_id",
            sa.String(length=64),
            nullable=True,
            comment="For messages with role='tool', this links back to the specific tool_call_id.",
        ),
    )

    # Ensure function_call is NOT NULL
    safe_alter_column(
        "messages", "function_call", existing_type=mysql.TEXT(), nullable=False
    )

    # --- Table: runs ---
    add_column_if_missing(
        "runs",
        sa.Column(
            "current_turn",
            sa.Integer(),
            server_default="0",
            nullable=True,
            comment="The current iteration count of the autonomous loop.",
        ),
    )
    add_column_if_missing(
        "runs",
        sa.Column(
            "max_turns",
            sa.Integer(),
            server_default="1",
            nullable=True,
            comment="Snapshot of Assistant.max_turns at run creation.",
        ),
    )
    add_column_if_missing(
        "runs",
        sa.Column(
            "agent_mode",
            sa.String(length=32),
            server_default="standard",
            nullable=True,
            comment="Snapshot of Assistant.agent_mode at run creation.",
        ),
    )

    # Alter truncation_strategy to be nullable
    safe_alter_column(
        "runs",
        "truncation_strategy",
        existing_type=mysql.VARCHAR(length=16),
        nullable=True,
        existing_server_default=sa.text("'auto'"),
    )


def downgrade() -> None:
    """Downgrade schema safely."""

    # --- Table: runs ---
    safe_alter_column(
        "runs",
        "truncation_strategy",
        existing_type=mysql.VARCHAR(length=16),
        nullable=False,
        existing_server_default=sa.text("'auto'"),
    )
    drop_column_if_exists("runs", "agent_mode")
    drop_column_if_exists("runs", "max_turns")
    drop_column_if_exists("runs", "current_turn")

    # --- Table: messages ---
    safe_alter_column(
        "messages", "function_call", existing_type=mysql.TEXT(), nullable=True
    )
    drop_column_if_exists("messages", "tool_call_id")
    drop_column_if_exists("messages", "tool_calls")
    drop_column_if_exists("messages", "reasoning")

    # --- Table: assistants ---
    drop_column_if_exists("assistants", "agent_mode")
    drop_column_if_exists("assistants", "max_turns")

    # --- Table: actions ---
    # Safe index drop
    bind = op.get_bind()
    insp = inspect(bind)
    indexes = [idx["name"] for idx in insp.get_indexes("actions")]
    if "ix_actions_tool_call_id" in indexes:
        op.drop_index(op.f("ix_actions_tool_call_id"), table_name="actions")

    drop_column_if_exists("actions", "turn_index")
    drop_column_if_exists("actions", "tool_call_id")
