"""remove_tools_table_and_associations

Revision ID: ac1498a9642c
Revises: 9314d4058f78
Create Date: 2026-01-25 02:09:10.112629

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy import inspect
from sqlalchemy.dialects import mysql

# Import the safe DDL helpers
from migrations.utils.safe_ddl import (add_column_if_missing,
                                       drop_column_if_exists, has_table,
                                       safe_alter_column)

# revision identifiers, used by Alembic.
revision: str = "ac1498a9642c"
down_revision: Union[str, None] = "9314d4058f78"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema safely."""
    bind = op.get_bind()
    insp = inspect(bind)

    # 1. Drop Foreign Key on 'actions' (if exists)
    # We must check strictly because in a 'Fresh Start', the table might already match the new schema
    if has_table("actions"):
        # Fetch existing FKs
        existing_fks = [fk["name"] for fk in insp.get_foreign_keys("actions")]

        # We look for the specific constraint name generated by MySQL or Alembic
        # (actions_ibfk_2 is from your autogen, but we also check for generic naming just in case)
        target_fks = ["actions_ibfk_2", "actions_tool_id_fkey"]

        for fk_name in target_fks:
            if fk_name in existing_fks:
                op.drop_constraint(fk_name, "actions", type_="foreignkey")
                print(f"[Alembic-safeDDL] ✅ Dropped constraint: {fk_name}")

    # 2. Drop Column 'tool_id' from 'actions'
    drop_column_if_exists("actions", "tool_id")

    # 3. Drop Association Table 'assistant_tools'
    if has_table("assistant_tools"):
        op.drop_table("assistant_tools")
        print("[Alembic-safeDDL] ✅ Dropped table: assistant_tools")
    else:
        print("[Alembic-safeDDL] ⚠️ Skipped – table not found: assistant_tools")

    # 4. Drop 'tools' table
    # (Dropping the table automatically drops 'ix_tools_id', so we don't need explicit index drop)
    if has_table("tools"):
        op.drop_table("tools")
        print("[Alembic-safeDDL] ✅ Dropped table: tools")
    else:
        print("[Alembic-safeDDL] ⚠️ Skipped – table not found: tools")

    # 5. Alter 'messages' columns
    # Make function_call nullable=False
    safe_alter_column(
        "messages", "function_call", existing_type=mysql.TEXT(), nullable=False
    )

    # Change reasoning type to Long Text
    safe_alter_column(
        "messages",
        "reasoning",
        existing_type=mysql.LONGTEXT(),
        type_=sa.Text(length=4294967295),
        existing_comment="Stores the internal 'thinking' or reasoning tokens from the model.",
        nullable=True,
    )


def downgrade() -> None:
    """Downgrade schema safely."""
    bind = op.get_bind()
    insp = inspect(bind)

    # 1. Revert 'messages' columns
    safe_alter_column(
        "messages",
        "reasoning",
        existing_type=sa.Text(length=4294967295),
        type_=mysql.LONGTEXT(),
        existing_comment="Stores the internal 'thinking' or reasoning tokens from the model.",
        nullable=True,
    )

    safe_alter_column(
        "messages", "function_call", existing_type=mysql.TEXT(), nullable=True
    )

    # 2. Recreate 'tools' table
    if not has_table("tools"):
        op.create_table(
            "tools",
            sa.Column("id", mysql.VARCHAR(length=64), nullable=False),
            sa.Column("name", mysql.VARCHAR(length=128), nullable=False),
            sa.Column("type", mysql.VARCHAR(length=64), nullable=False),
            sa.Column("function", mysql.JSON(), nullable=True),
            sa.PrimaryKeyConstraint("id"),
            mysql_collate="utf8mb4_0900_ai_ci",
            mysql_default_charset="utf8mb4",
            mysql_engine="InnoDB",
        )
        op.create_index("ix_tools_id", "tools", ["id"], unique=False)
        print("[Alembic-safeDDL] ✅ Re-created table: tools")

    # 3. Recreate 'assistant_tools' table
    if not has_table("assistant_tools"):
        op.create_table(
            "assistant_tools",
            sa.Column("assistant_id", mysql.VARCHAR(length=64), nullable=True),
            sa.Column("tool_id", mysql.VARCHAR(length=64), nullable=True),
            sa.ForeignKeyConstraint(
                ["assistant_id"], ["assistants.id"], name="assistant_tools_ibfk_1"
            ),
            sa.ForeignKeyConstraint(
                ["tool_id"], ["tools.id"], name="assistant_tools_ibfk_2"
            ),
            mysql_collate="utf8mb4_0900_ai_ci",
            mysql_default_charset="utf8mb4",
            mysql_engine="InnoDB",
        )
        print("[Alembic-safeDDL] ✅ Re-created table: assistant_tools")

    # 4. Add 'tool_id' back to 'actions'
    add_column_if_missing(
        "actions", sa.Column("tool_id", mysql.VARCHAR(length=64), nullable=True)
    )

    # 5. Re-add Foreign Key to 'actions'
    # Check if constraint exists before adding to avoid duplicate error
    if has_table("actions"):
        existing_fks = [fk["name"] for fk in insp.get_foreign_keys("actions")]
        if "actions_ibfk_2" not in existing_fks:
            op.create_foreign_key(
                "actions_ibfk_2", "actions", "tools", ["tool_id"], ["id"]
            )
            print("[Alembic-safeDDL] ✅ Re-created foreign key: actions_ibfk_2")
