from entities_api.orchestration.instructions.definitions import LEVEL_3_WEB_USE_INSTRUCTIONS

L2_INSTRUCTIONS = [
    "TOOL_USAGE_PROTOCOL",
    "FUNCTION_CALL_FORMATTING",
    "FUNCTION_CALL_WRAPPING",
]

L3_INSTRUCTIONS = [
    "L3_IDENTITY",
    "L3_PLANNING_PROTOCOL",
    "TOOL_DECISION_PROTOCOL",
    "L3_PARALLEL_EXECUTION",
    "TOOL_USAGE_PROTOCOL",
    "FUNCTION_CALL_FORMATTING",
    "FUNCTION_CALL_WRAPPING",
    "L3_SYNTAX_ENFORCEMENT",
]


LEVEL_4_SUPERVISOR_INSTRUCTIONS = [
    "L4_SUPERVISOR_IDENTITY",
    "L4_EXECUTION_PROTOCOL",
    "L4_SUPERVISOR_CONSTRAINTS",
    "TOOL_USAGE_PROTOCOL",
    "FUNCTION_CALL_FORMATTING",
    "FUNCTION_CALL_WRAPPING",
]


L4_RESEARCH_INSTRUCTIONS = [
    "L4_WORKER_IDENTITY",
    "L4_TOOL_CHEATSHEET",
    "L4_EXECUTION_ALGORITHM",
    "L4_STOPPING_CRITERIA",
    "L4_OUTPUT_FORMAT" "TOOL_STRATEGY",
    "BATCH_OPERATIONS",
    "L3_PARALLEL_EXECUTION",
    "TOOL_USAGE_PROTOCOL",
    "FUNCTION_CALL_FORMATTING",
    "FUNCTION_CALL_WRAPPING",
]


L3_WEB_USE_INSTRUCTIONS = [
    # "WEB_CORE_IDENTITY",
    "TOOL_STRATEGY",
    "CONTEXT_MANAGEMENT",
    "BATCH_OPERATIONS",
    "ERROR_HANDLING",
    "STOP_RULE",
]


NO_CORE_INSTRUCTIONS = ["NONE"]
